### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by RoboMWM** [MLG-Fortress/ChesterPlugin#1]
``` txt
[15:46:30] [Async Chat Thread - #16/ERROR]: Could not pass event AsyncPlayerChatEvent to Chester v2.4
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-432]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched.jar:git-PaperSpigot-432]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-432]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [patched.jar:git-PaperSpigot-432]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:483) [patched.jar:git-PaperSpigot-432]
    at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1111) [patched.jar:git-PaperSpigot-432]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1026) [patched.jar:git-PaperSpigot-432]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched.jar:git-PaperSpigot-432]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
    at info.gomeow.chester.Chester.onChat(Chester.java:159) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor956.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-432]
    ... 12 more
```

**Comment by RoboMWM** [comment]
Above commit fixes this.
